"""
Proves standalone_pipeline.PixelClassificationPipeline produces the same
output as the real ilastik.experimental.api.PixelClassificationPipeline, on
real trained .ilp projects - both raw probability maps and binarized
(argmax) label maps.

Requires the FULL ilastik/lazyflow/vigra/fastfilters stack - see "Reference
environment setup" in ../PLAN.md for the exact recipe. That stack needs
Python >= 3.11 (lazyflow/utility/data_semantics.py uses enum.StrEnum) and a
few extra pip packages beyond vigra/fastfilters/h5py/numpy. It also pulls in
z5py (irrelevant here - only used for N5 I/O) and expects an editable
install for ilastik._version (normally generated by `pip install -e .`);
both are stubbed below rather than actually required, so a plain source
checkout works.

Usage:
    python compare_against_real_pipeline.py <project.ilp> <image_file> \\
        [--dims y x] [--crop Y0 Y1 X0 X1] [--atol 1e-5]

Example (from repo root):
    python tools/standalone_pixel_classification/dev_validation/compare_against_real_pipeline.py \\
        notebooks/pixel_classification_api/pc.ilp \\
        notebooks/pixel_classification_api/2d_cells_apoptotic_1channel.png \\
        --crop 300 364 300 364
"""
import argparse
import os
import sys
import types

import numpy as np

TOOL_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO_ROOT = os.path.dirname(os.path.dirname(TOOL_DIR))

# Only used when the checkout has no generated ilastik/_version.py. See
# _prepare_real_ilastik_imports() for why the value matters.
STUB_ILASTIK_VERSION = "1.4.1"


def _prepare_real_ilastik_imports():
    if "z5py" not in sys.modules:
        stub = types.ModuleType("z5py")
        stub.set_json_encoder = lambda *a, **kw: None
        sys.modules["z5py"] = stub

    # ilastik/__init__.py does `from ._version import version`, which a
    # pre-registered sys.modules entry satisfies - so we can supply the version
    # without writing anything into the checkout. Writing a real
    # ilastik/_version.py here would outlive this script: ilastik.__version__
    # would become that stub value for everything else run from this checkout,
    # and isVersionCompatible() (ilastik/__init__.py) compares only (major,
    # minor), so a "0.0.0.dev0" stub makes every real 1.4.x project file look
    # incompatible. Leave a genuine _version.py (from `pip install -e .`) alone.
    version_path = os.path.join(REPO_ROOT, "ilastik", "_version.py")
    if not os.path.exists(version_path) and "ilastik._version" not in sys.modules:
        stub = types.ModuleType("ilastik._version")
        # Must be in the 1.4 series: isVersionCompatible() requires the running
        # version and the project's version to both be in its compatible set.
        stub.version = STUB_ILASTIK_VERSION
        sys.modules["ilastik._version"] = stub

    if REPO_ROOT not in sys.path:
        sys.path.insert(0, REPO_ROOT)


def load_real_pipeline(ilp_path: str):
    _prepare_real_ilastik_imports()
    from ilastik.experimental.api import PixelClassificationPipeline as RealPipeline

    return RealPipeline.from_ilp_file(ilp_path)


def load_standalone_pipeline(ilp_path: str):
    if TOOL_DIR not in sys.path:
        sys.path.insert(0, TOOL_DIR)
    from standalone_pipeline import PixelClassificationPipeline as StandalonePipeline

    return StandalonePipeline.from_ilp_file(ilp_path)


def run_comparison(ilp_path: str, image_path: str, dims, crop, atol: float, rtol: float) -> bool:
    import imageio.v3 as iio

    image = iio.imread(image_path)
    if crop is not None:
        y0, y1, x0, x1 = crop
        image = image[y0:y1, x0:x1]

    print(f"Project:  {ilp_path}")
    print(f"Image:    {image_path}  shape={image.shape} dtype={image.dtype}" + (f"  (cropped to {crop})" if crop else ""))
    print(f"Dims:     {dims}")
    print()

    print("Running real ilastik.experimental.api.PixelClassificationPipeline ...")
    real_pipeline = load_real_pipeline(ilp_path)
    import xarray

    real_probs = np.asarray(real_pipeline.get_probabilities(xarray.DataArray(image, dims=dims)).values)
    print(f"  done, output shape {real_probs.shape}")

    print("Running standalone_pipeline.PixelClassificationPipeline (no vigra/fastfilters/lazyflow) ...")
    standalone_pipeline = load_standalone_pipeline(ilp_path)
    standalone_probs = standalone_pipeline.get_probabilities(image, dims=dims)
    standalone_probs = np.asarray(
        standalone_probs.values if hasattr(standalone_probs, "values") else standalone_probs
    )
    print(f"  done, output shape {standalone_probs.shape}")
    print()

    if real_probs.shape != standalone_probs.shape:
        print(f"SHAPE MISMATCH: real={real_probs.shape} standalone={standalone_probs.shape}")
        return False

    # --- Raw probabilities ---
    diff = np.abs(real_probs - standalone_probs)
    max_diff = diff.max()
    mean_diff = diff.mean()
    p999_diff = np.percentile(diff, 99.9)
    probs_ok = np.allclose(real_probs, standalone_probs, atol=atol, rtol=rtol)

    print("=== Raw probabilities ===")
    print(f"  max abs diff:        {max_diff:.3e}")
    print(f"  mean abs diff:       {mean_diff:.3e}")
    print(f"  99.9th pct abs diff: {p999_diff:.3e}")
    print(f"  {'OK' if probs_ok else 'MISMATCH'} (atol={atol:.1e}, rtol={rtol:.1e})")
    print()

    # --- Binarized (argmax) predictions ---
    real_labels = np.argmax(real_probs, axis=-1)
    standalone_labels = np.argmax(standalone_probs, axis=-1)
    mismatch_mask = real_labels != standalone_labels
    n_mismatch = int(mismatch_mask.sum())
    n_total = mismatch_mask.size
    labels_ok = n_mismatch == 0

    print("=== Binarized (argmax) predictions ===")
    print(f"  mismatched pixels: {n_mismatch} / {n_total} ({100 * n_mismatch / n_total:.4f}%)")
    print(f"  {'OK' if labels_ok else 'MISMATCH'}")
    print()

    overall_ok = probs_ok and labels_ok
    print("ALL OK" if overall_ok else "FAILED")
    return overall_ok


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("ilp_path")
    parser.add_argument("image_path")
    parser.add_argument("--dims", nargs="+", default=["y", "x"], help="Axis dims of the image file, e.g. y x or z y x")
    parser.add_argument("--crop", nargs=4, type=int, metavar=("Y0", "Y1", "X0", "X1"), default=None)
    parser.add_argument("--atol", type=float, default=1e-4)
    parser.add_argument("--rtol", type=float, default=1e-3)
    args = parser.parse_args()

    ok = run_comparison(args.ilp_path, args.image_path, tuple(args.dims), args.crop, args.atol, args.rtol)
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
