"""
Proves standalone_pipeline.PixelClassificationPipeline produces the same
*decisions* as the real ilastik.experimental.api.PixelClassificationPipeline,
on real trained .ilp projects.

Requires the FULL ilastik/lazyflow/vigra/fastfilters stack - see "Reference
environment setup" in ../PLAN.md for the exact recipe. That stack needs
Python >= 3.11 (lazyflow/utility/data_semantics.py uses enum.StrEnum) and a
few extra pip packages beyond vigra/fastfilters/h5py/numpy. It also pulls in
z5py (irrelevant here - only used for N5 I/O) and expects an editable
install for ilastik._version (normally generated by `pip install -e .`);
both are stubbed below rather than actually required, so a plain source
checkout works.

Acceptance metric: NOT raw max-abs-diff on probabilities. "fastfilters" isn't
a single fixed numerical target to begin with - it does runtime CPU dispatch
(AVX2+FMA / AVX / SSE), those paths don't produce identical floats, and
vigra/fastfilters don't bit-match each other either; a real ilastik install
already doesn't reproduce its own probabilities bit-for-bit across machines.
Chasing ULP-identity against one specific reference run is chasing a moving
target. The metric that actually matters: does a probability residual ever
flip an argmax decision that the real pipeline itself was confident about?
So the check here is:

  1. Binarized (argmax) prediction flip rate between the two pipelines.
  2. For every flipped pixel, the REAL pipeline's own decision margin
     (top1 probability - top2 probability) at that pixel - i.e. how
     confident the reference answer even was.
  3. PASS iff every flip happened at a pixel where the real pipeline's own
     margin was already <= --margin-threshold (default 0.1): those are
     inherently ambiguous/near-coin-flip pixels (often exactly 0.5/0.5)
     where a ~1e-6-level feature-computation difference between two
     independently-implemented convolution pipelines flipping the decision
     is expected and not a correctness bug. A flip at a pixel the real
     pipeline was actually confident about (margin > threshold) is a real
     problem and fails the check.

Raw probability diff stats are still printed, but informationally only - not
part of the pass/fail decision.

Usage:
    python compare_against_real_pipeline.py <project.ilp> <image_file> \\
        [--dims y x] [--crop Y0 Y1 X0 X1] [--margin-threshold 0.1]

Example (from repo root):
    python tools/standalone_pixel_classification/dev_validation/compare_against_real_pipeline.py \\
        notebooks/pixel_classification_api/pc.ilp \\
        notebooks/pixel_classification_api/2d_cells_apoptotic_1channel.png
"""
import argparse
import os
import sys
import types

import numpy as np

TOOL_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO_ROOT = os.path.dirname(os.path.dirname(TOOL_DIR))


def _prepare_real_ilastik_imports():
    if "z5py" not in sys.modules:
        stub = types.ModuleType("z5py")
        stub.set_json_encoder = lambda *a, **kw: None
        sys.modules["z5py"] = stub

    version_path = os.path.join(REPO_ROOT, "ilastik", "_version.py")
    if not os.path.exists(version_path):
        with open(version_path, "w") as f:
            f.write('version = "0.0.0.dev0"\n')  # dev-only stub; ilastik/_version.py is gitignored

    if REPO_ROOT not in sys.path:
        sys.path.insert(0, REPO_ROOT)


def load_real_pipeline(ilp_path: str):
    _prepare_real_ilastik_imports()
    from ilastik.experimental.api import PixelClassificationPipeline as RealPipeline

    return RealPipeline.from_ilp_file(ilp_path)


def load_standalone_pipeline(ilp_path: str):
    if TOOL_DIR not in sys.path:
        sys.path.insert(0, TOOL_DIR)
    from standalone_pipeline import PixelClassificationPipeline as StandalonePipeline

    return StandalonePipeline.from_ilp_file(ilp_path)


def run_comparison(ilp_path: str, image_path: str, dims, crop, margin_threshold: float) -> bool:
    import imageio.v3 as iio

    image = iio.imread(image_path)
    if crop is not None:
        y0, y1, x0, x1 = crop
        image = image[y0:y1, x0:x1]

    print(f"Project:  {ilp_path}")
    print(f"Image:    {image_path}  shape={image.shape} dtype={image.dtype}" + (f"  (cropped to {crop})" if crop else ""))
    print(f"Dims:     {dims}")
    print()

    print("Running real ilastik.experimental.api.PixelClassificationPipeline ...")
    real_pipeline = load_real_pipeline(ilp_path)
    import xarray

    real_probs = np.asarray(real_pipeline.get_probabilities(xarray.DataArray(image, dims=dims)).values)
    print(f"  done, output shape {real_probs.shape}")

    print("Running standalone_pipeline.PixelClassificationPipeline (no vigra/fastfilters/lazyflow) ...")
    standalone_pipeline = load_standalone_pipeline(ilp_path)
    standalone_probs = standalone_pipeline.get_probabilities(image, dims=dims)
    standalone_probs = np.asarray(
        standalone_probs.values if hasattr(standalone_probs, "values") else standalone_probs
    )
    print(f"  done, output shape {standalone_probs.shape}")
    print()

    if real_probs.shape != standalone_probs.shape:
        print(f"SHAPE MISMATCH: real={real_probs.shape} standalone={standalone_probs.shape}")
        return False

    # --- Raw probabilities (informational only - see module docstring for why
    #     this isn't the pass/fail gate) ---
    diff = np.abs(real_probs - standalone_probs)
    print("=== Raw probabilities (informational) ===")
    print(f"  max abs diff:        {diff.max():.3e}")
    print(f"  mean abs diff:       {diff.mean():.3e}")
    print(f"  99.9th pct abs diff: {np.percentile(diff, 99.9):.3e}")
    print()

    # --- Binarized (argmax) predictions vs. real pipeline's own confidence ---
    real_labels = np.argmax(real_probs, axis=-1)
    standalone_labels = np.argmax(standalone_probs, axis=-1)
    mismatch_mask = real_labels != standalone_labels
    n_mismatch = int(mismatch_mask.sum())
    n_total = mismatch_mask.size

    real_sorted = np.sort(real_probs, axis=-1)
    real_margin = real_sorted[..., -1] - real_sorted[..., -2]  # real pipeline's own top1-top2 gap

    print("=== Binarized (argmax) predictions - acceptance metric ===")
    print(f"  flipped pixels: {n_mismatch} / {n_total} ({100 * n_mismatch / n_total:.4f}%)")

    if n_mismatch:
        flip_margins = real_margin[mismatch_mask]
        print(
            f"  real-pipeline decision margin at flipped pixels: "
            f"min={flip_margins.min():.4f} mean={flip_margins.mean():.4f} max={flip_margins.max():.4f}"
        )
        confident_flips = flip_margins > margin_threshold
        n_confident_flips = int(confident_flips.sum())
        print(f"  of those, flips where the real pipeline was CONFIDENT (margin > {margin_threshold}): {n_confident_flips}")
        labels_ok = n_confident_flips == 0
    else:
        labels_ok = True
        print("  no flips")

    print(
        f"  {'OK' if labels_ok else 'FAILED'} - passes iff no flip occurs at a pixel the real pipeline was "
        f"confident about (margin > {margin_threshold}); flips at already-ambiguous pixels "
        "(often exactly tied) are expected and don't count as failures."
    )
    print()

    print("ALL OK" if labels_ok else "FAILED")
    return labels_ok


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("ilp_path")
    parser.add_argument("image_path")
    parser.add_argument("--dims", nargs="+", default=["y", "x"], help="Axis dims of the image file, e.g. y x or z y x")
    parser.add_argument("--crop", nargs=4, type=int, metavar=("Y0", "Y1", "X0", "X1"), default=None)
    parser.add_argument(
        "--margin-threshold",
        type=float,
        default=0.1,
        help="An argmax flip only fails the check if the real pipeline's own top1-top2 "
        "probability margin at that pixel exceeds this (default 0.1).",
    )
    args = parser.parse_args()

    ok = run_comparison(args.ilp_path, args.image_path, tuple(args.dims), args.crop, args.margin_threshold)
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
